name: CMake_Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 
 build:
 
  runs-on: ubuntu-latest
  permissions:
    contents: write

  steps:
  - uses: actions/checkout@v4
    
  - name: Build 
    run: |
      cmake -H. -B_build
      cmake --build _build
      
  - name: my_exe
    run: |
      echo -e "1\n2\n1" | ${{github.workspace}}/_build/master
 
  - name: package
    run: cmake --build ${{github.workspace}}/_build --target package
  
  - name: package_source
    run: cmake --build ${{github.workspace}}/_build --target package_source

  - name: Artifact
    uses: actions/upload-artifact@v4
    with:
        name: master
        path: ${{github.workspace}}/_build/master

  - name: Make a release
    uses: ncipollo/release-action@v1.14.0
    with:
        artifacts: "${{github.workspace}}/_build/*.deb,${{github.workspace}}/_build/*.tar.gz,${{github.workspace}}/_build/*.zip"
        tag: 1.1.0
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: tru
